os: linux
dist: xenial
language: java
jdk:
    - openjdk8

install: true
script: 
    - mvn clean package -Dmaven.test.skip=true
    - mvn jasypt:load test -Djasypt.plugin.path="file:src/main/resources/application.yml" -Djasypt.encryptor
    - .password="$JASYPT_ENCRYPT_KEY"

after_success:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN