# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://emm-dbserver-jp1.mysql.database.azure.com:3306/emm_mall
    username: emmettwoo
    password: g&2MQaLxL@d3Um%^

# Logger Config
logging:
  level:
    top.woohoo.mall: debug